# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v3
      with:
        # The version of Lua to install, must be available on https://www.lua.org/ftp/ or http://luajit.org/download.html
        luaVersion: 5.3.5 # optional, default is 5.3

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v2
      with:
        # The version of LuaRocks to install, must be available on https://luarocks.github.io/luarocks/releases/
        luaRocksVersion: 3.3.1 # optional, default is 3.2.0

    - name: Install dkjson
      run: luarocks install dkjson

    - name: Build and upload to luarocks
      run: luarocks upload --api-key=${API_KEY} *.rockspec
      env:
         API_KEY: ${{secrets.luarocks_api_key}}
