name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: 5.3.5 # optional, default is 5.3

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4
      with:
        luaRocksVersion: 3.3.1 # optional, default is 3.2.0

    - name: Install dkjson
      run: luarocks install dkjson

    - name: Pack
      run: luarocks pack *.rockspec

    - name: Build and upload to luarocks
      run: luarocks upload --api-key=${API_KEY} *.rockspec
      env:
         API_KEY: ${{secrets.luarocks_api_key}}
